### ISSUE TITLE
请教一些关于

### ISSUE THREAD

**Issue by Z-Xiong** [wujin-alex/drone-object-geolocation#1]
非常感谢您开源的这个项目，我有一些问题想要请教您。
1、需要提前做相机标定吗？
2、这里的激光传感器是不是和相机光轴平行呢？
3、激光传感器的坐标需要转换到相机坐标系下吗？
4、如果物体不在图像中心 的话需要修改哪里呢？
5、从焦距f到像素fx是如何计算的。为什么“如果没有校准，fx=focal/sigma，其中sigma为像元大小”。

**Comment by AlexHAHA** [comment]
1. 相机需要标定，当然对于无人机吊舱来说这里面的相机一般比较贵，出厂标定好了，可以先看看实际效果，不满意再标定。标定的本质也就是得到K矩阵
2. 用来测量与物体距离的激光传感器是需要与光轴平行的
3. 为了精确提高精度的话需要，激光传感器安装位置在相机坐标系下就是一个平移向量而已，而且向量模很小，不转到相机坐标系下也可以。无人机飞的一般很高，对精度影响不大。
4. 算法里面已经考虑了不在中心的情况了，算法不需要修改，是完备的
5. 焦距到像素之间关系就是根据K矩阵，也就是下面参数，这个要么根据标定得到。相机供应商也会提供








| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月18日 11:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [wujin-alex/drone-object-geolocation] 请教一些关于 (Issue #1) |

非常感谢您开源的这个项目，我有一些问题想要请教您。
1、需要提前做相机标定吗？
2、这里的激光传感器是不是和相机光轴平行呢？
3、激光传感器的坐标需要转换到相机坐标系下吗？
4、如果物体不在图像中心 的话需要修改哪里呢？
5、从焦距f到像素fx是如何计算的。

**Comment by Z-Xiong** [comment]
感谢您的回答!我再仔细研究一下。

**Comment by Z-Xiong** [comment]
我已知相机
焦距 f=2.35mm
FOV-H fov_w=93度
FOV-V fov_h=76度
获取视频流的图片大小是w=640， h=360。
计算fx, fy:
ccd_w = 2 * f * tan(fov_w / 2 *pi / 180)
ccd_h = 2 * f * tan(fov_h / 2 * pi / 180)
sigma_x = ccd_w / w
sigma_y = ccd_h / h
fx = f / sigma_x
fy = f / sigma_y

大佬，能帮我看看，我这样计算fx，fy对吗？

**Comment by Z-Xiong** [comment]
请问无人机姿态角已知，相机在无人机机身上，那相机的姿态角是不是一直是(0,0,0)，还是说相机的姿态角与无人机是一样的？

**Comment by Z-Xiong** [comment]
问题已经解决。再次感谢您开源的代码。

> 我仔细看了一下代码，请问从相机坐标系到机体坐标系，是不是只考虑了旋转矩阵，没有考虑平移矩阵，您是默认相机和机体是共用原点吗?

共用原点。

> 请问无人机姿态角已知，按照机体的z轴对应相机的y轴，机体y轴对应相机x轴，机体x轴对应相机z轴，如果这个时候相机固定在机身上，不做旋转。相机的姿态角如何通过机体姿态角求得呢。相机的姿态角是？ 1、一直是(0,0,0) 2、相机的姿态角与无人机是一样的。 3、roll_c=yaw_b；pitch_c= pitch_b；yaw_c=roll_b。

（1）如果规定相机坐标系与机体坐标系xyz指向相同，相机在机身上固定不动。则相机的姿态角为(0,0,0)，对应从相机到机体的旋转矩阵为:
[1,0,0;
0,1,0;
0,0,1]；
（2）如果规定相机坐标系与机体坐标系分别对应关系是Xc=Zb, Yc=Zb, Zc=Yb的话，相机在机身上固定不动，则相机姿态角为(-PI/2, PI, -PI/2)，对应从相机到机体的旋转矩阵为:
[0,0,1;
1,0,0;
0,1,0]。
代码中使用了定义(1)。

**Comment by AlexHAHA** [comment]
应该是的，当然代码写完没有充分测试。
你可以根据实际情况进行修改。自己增加测试函数判断最终结果是否是预期的。
这个项目代码有一定bug，不过总体上思路和算法公式没太大问题。后续有时间我再优化下。最近忙着飞控开发，没有维护这个项目了。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月18日 19:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wujin-alex/drone-object-geolocation] 请教一些关于 (Issue #1) |

我仔细看了一下代码，请问从相机坐标系到机体坐标系，是不是只考虑了旋转矩阵，没有考虑平移矩阵，您是默认相机和机体是共用原点吗?

**Comment by Z-Xiong** [comment]
> 应该是的，当然代码写完没有充分测试。 你可以根据实际情况进行修改。自己增加测试函数判断最终结果是否是预期的。 这个项目代码有一定bug，不过总体上思路和算法公式没太大问题。后续有时间我再优化下。最近忙着飞控开发，没有维护这个项目了。 | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年07月18日 19:00 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [wujin-alex/drone-object-geolocation] 请教一些关于 (Issue #1) | 我仔细看了一下代码，请问从相机坐标系到机体坐标系，是不是只考虑了旋转矩阵，没有考虑平移矩阵，您是默认相机和机体是共用原点吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

感谢，我把理论公式推导了一遍，代码的实现基本没有什么问题。您说的bug是哪方面的呢？请问如果实际工程上没有激光测距的情况下，使用气压计测高误差较大，有什么优化思路吗？

**Comment by Z-Xiong** [comment]
你好，我遇到一个问题，就是theta_2=90度的时候，Lt是无穷大。这里是个bug。当theta_2=90度的时候能不能根据焦距求呢？

**Comment by AlexHAHA** [comment]
这个代码太久没看了，最近一直在忙飞控开发。
主要是代码没有经过充分测试，可能有一些潜在bug，一般性使用没问题。

关于你说的90度的问题，在做测试的时候可能遇到这个问题，如果实际使用吊舱时，传感器读的数据不会正好是90，，为了保险，如果很接近90，你可以让它等于90.01这种人为逻辑操作，避免出现极值。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月27日 15:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wujin-alex/drone-object-geolocation] 请教一些关于 (Issue #1) |

你好，我遇到一个问题，就是theta_2=90度的时候，Lt是无穷大。这里是个bug。当theta_2=90度的时候能不能根据焦距求呢？
